### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/EmilyDickinson16#1]
I am available after class on Mondays and Wednesdays until 1pm.  I am also available on Tuesdays until 1pm and Thursdays until 11am.  Just letting everyone know!  Have a fantastic Sunday!!

**Comment by brookestewart** [comment]
I'm available after 3 on Mondays and Wednesdays. I can also do anytime before 2 on Tuesdays and Thursdays.

**Comment by alexthattalks** [comment]
I am available Mondays and Wednesdays from 3-5:30. I am also available after class until 1, but I have that time reserved if I need to do something for my job. Other than that, I work all day Tuesday and Thursday.

**Comment by blawrence719** [comment]
I'm usually available Mondays 2:30-4:00, Tuesdays after 2:30, Thursdays after 11:30, and Fridays after 1.

**Comment by ebeshero** [comment]
@amielnicki @blawrence719  @nlottig94  @brookestewart Hmmm. This is difficult, team Dickinson! I'm teaching two classes on M W F afternoons, so that means I'm only available on M W F at these times:
- after our class until around 1ish
- between 3 - 3:45ish on M W. 
- after 5:15 on M W
- anytime after 3 on F (because my late afternoon class is only M W).

I could be available any time of day on Tues. or Thurs., though sometimes I have meetings over the lunch hour--so morning or afternoon would be fine for me. 

Looking at your schedules, I'm not really sure there's a good time where the stars align and we all can meet! \* May I ask if everyone might be free for about an hour on **Fridays at 3 PM**?

 If that works, I'll reschedule the DH instructor meeting so we can have regular meetings then--but let me know if it's out of the question for you!

**Comment by nlottig94** [comment]
I cannot do Fridays at 3pm.  I have to work.  I'm sorry.

**Comment by brookestewart** [comment]
I also have to work on Fridays.

**Comment by ebeshero** [comment]
@nlottig94 @blawrence719 @brookestewart @amielnicki I think we might just meet briefly right after our class, to get everyone started. Meetings don't need to be long since we can coordinate tasks here in GitHub. But I do need to show you some things about the Dickinson files and point out some things you could do with the poems, connected with your project proposals.
