### ISSUE TITLE
Home, About, and Conclusion Pages (Brooke Lawrence's Stuff)

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/EmilyDickinson16#20]
Reminder to self: work on analysis and paragraph for homepage.

**Comment by blawrence719** [comment]
@ebeshero It's sad to admit, but I forget the rules for writing html. I'm trying to include examples from the poems. How would I do this? I have them as `<lg>` and `<l>` right now and it gives me an error.

**Comment by ebeshero** [comment]
Aha! Are you trying to include some sample markup from our TEI, to **display it in your HTML pages about the Dickinson project**? That is a really great idea (and I hope it's what you're trying to do). What has to happen is you need a special HTML element for holding a block of pre-formatted text (really to keep your line-breaks in place, though you know?! It might hold indentations intact too re that other indentation issue we were talking about). That element is `<pre>`. Inside it, plop your XML code, but you are still going to see validation errors bc `<lg>` and `<l>` are not HTML elements. But you just want to **represent** these elements, not treat them **as** elements. So what you do is change the angle brackets into special character codes so the code parser doesn't try to read them as elements--thus:

```
&lt;  (in place of <)

&gt;  (in place of >)

```

Don't replace those by hand. In oXygen, highlight the text inside your `<pre>` element, and do a localized find and replace for the angle brackets.

You may want to write some CSS to control the look and feel of your `<pre>` blocks. For an example, take a look at one of our newtFire assignment pages with blocks of code on them, like this one:
http://newtfire.org/dh/SVGExercise2_Alice.html and view page source (and check out the CSS).

Is this what you needed, or do I have your question all wrong?

**Comment by blawrence719** [comment]
@ebeshero @amielnicki I've pushed my file with a rough draft of the conclusion in case we wanted it up tomorrow for our presentation or if Dr. B wants to read through the conclusion and suggest any changes/additions.

**Comment by ebeshero** [comment]
@blawrence719 looks good--for now! Be ready to change/add as more pages come together and @brookestewart works on the dash study!

**Comment by ebeshero** [comment]
@blawrence719 Here are some resources that you will want to refer to and discuss on either the Home or About pages. You're telling the story of the Repurposing of two earlier Dickinson sites, but the very first one really deserves special attention for its daring originality:

Michele Ierardi's site: This the main site we are repurposing, and I did a miserable hack job of it, which your team professionalized! http://www.cs.virginia.edu/~ajf2j/emily/stab.html 

For more information on the print publication history of Dickinson's poems: https://www.emilydickinsonmuseum.org/posthumous_publication

And for the source of the manuscript images of the Poem 11 (the version to Susan): see the Emily Dickinson Archive: http://www.edickinson.org/  You want to talk about this and send people here because it's the main archive where readers can find any manuscript image and see transcripts of all the poems. But it's not easy to study these by fascicle the way we're doing up close on this site, and you want to comment on what we're able to share with readers with our interface. Invite the reader to view a poem, pointing to the menu bar, and comment on a few things our reading interface accomplishes.

Look for pictures of things like Dickinson's fascicles bound together, maybe little images of Emily and Lavinia, and Susan(!)  Ask @amielnicki to have a look at your pictures, because he can probably style them to feature on the homepage.  Make an images directory for the home (index) page here on GitHub.

**Comment by ebeshero** [comment]
@blawrence719 @amielnicki  @nlottig94 Brooke Lawrence and I are thinking about how to differentiate among the following:

1) The home (index) page for the site (which we think should have pictures and not necessarily a LOT of text, but something to invite readers to explore the site.

2) A page describing the Repurposing you've accomplished, discussing Michele Ierardi's site as the (daring/pioneering!) origin. (I've just messaged Michele to ask her to send us a date when she prepared that site, but if she doesn't reply, we can just say, I think, that this was pre-2005, and done prior to XML with JavaScript that no longer functions.) AND you want to say something about the way she shares Dickinson's variants (SO not like what we see on http://edickinson.org !) This is telling a story, really.

3) A Methodology page describing the team's strategies  and approach to Dickinson. This one's ALL ABOUT Team Dickinson's work together. 

So, how to represent that on the menu hierarchy? Does this make sense as three pages? 
@blawrence719 is working on writing the Home and Repurposing pages, as well as the Conclusion page.

**Comment by brookestewart** [comment]
I think the Home page should definitely come first. Then the Repurposing could maybe go under the home tab on the website? It seems to be part of the introduction, but if we're keeping the Home page simple and inviting, I think it would work well under the home tab, where it would be separate, but still connected. To me, it would make sense for the methodology page to go under the about tab with our bios and assumptions (is there an assumptions page?) because it explains our more personal thought process. These are just my thoughts.

I will have the dash analysis page done either late late tonight or sometime tomorrow morning/early afternoon before my final. I apologize for the lack of activity, there have been some unforeseen events occurring lately!

@blawrence719 Dr. B mentioned proofreading the pages earlier. I can proofread yours, would you be willing to look over mine when it's finished?

**Comment by blawrence719** [comment]
@brookestewart The repurposing page has kind of become the about page. It's about telling the story of the different sites that this has gone through before it got to us and how we're doing everything (is this correct, @ebeshero ?). I'm unsure about what's going on with the assumptions page. I'm aiming to have majority of the homepage and repurposing/about page done tonight.

But yes, I can proofread your stuff.

**Comment by ebeshero** [comment]
@blawrence719 @brookestewart @amielnicki @nlottig94 Yes, what you say is what we spoke of for the Repurposing page. I am not sure about the Assumptions tab, and it could just be a placeholder that Alex would replace with one of these that you are developing!

**Comment by blawrence719** [comment]
@ebeshero I've pushed a file of my about page for now if you would like look at it and see if I'm going about this the right way.

**Comment by alexthattalks** [comment]
If the Repurposing will be on the main about page, then I will leave as is. I will replace the assupmtions page with methodologies as that is more all encompassing as to what the page will include.

**Comment by blawrence719** [comment]
I've also pushed a file of what my index looks like for now. Again, any feedback is welcome. 
*I realize I haven't pushed the pictures yet

**Comment by alexthattalks** [comment]
@blawrence719 We can certainly place those images side by side. Go ahead and push them to the GutHub! :)

**Comment by blawrence719** [comment]
I just pushed them. I can move them to a folder later

**Comment by alexthattalks** [comment]
Great! Thanks!! I pushed your about page to the web server. You can see it here: http://dickinson16.newtfire.org/about.html

**Comment by blawrence719** [comment]
Is it just me? - I can't see the about page or the dash svg page

**Comment by alexthattalks** [comment]
Try again, that was my bad. I pushed your info to the homepage too.

http://dickinson16.newtfire.org/
http://dickinson16.newtfire.org/about.html
http://dickinson16.newtfire.org/dash.html

You may need to hold the SHIFT key when reloading the web page, if your browser is caching older versions of the site.
