### ISSUE TITLE
Indentation in Versioning

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/EmilyDickinson16#21]
@blawrence719 I noticed that there are three spaces before the beginning of some lines, especially in poem 3. Are these the indentations? If so, does that work and should I fix my code to look like this? @amielnicki @nlottig94 @ebeshero any thoughts?

**Comment by blawrence719** [comment]
I believe there were two poems that I worked on that had versions that indented every other line and I wasn't sure how to code this, but the way that I did it didn't work. I just used a tab at the start of the line. I also wasn't sure if we wanted to represent this in our versions or how we would do that since our code gives the option of having two different versions sit side by side. I don't have my code open, but I put a comment at the top of the poems saying which versions were meant to be indented.

**Comment by ebeshero** [comment]
Yikes! Okay--the indentation is only in the print editions, right? If so, I would suggest we not worry about encoding or representing it, since we don't have a good way of doing that in our web interface where we are comparing the versions all together in one spot. (We don't need to worry about it bc we can show the print page layouts on click of our JavaScript buttons.) 

In XML and HTML you really can't control white space with blank spaces on the space bar: you only get two spaces that way max, and anything more disappears on the web. The way you'd control it is with CSS, so you'd want to mark elements to be indented with a special attribute that you can process with CSS to put, say extra padding of 5 pixels (or so) on your element to nudge it over. But our interface isn't really about honoring the print page layouts in our rendering of the poems, so I'd say let's delete the extra spaces and not worry about it here. @brookestewart @blawrence719
