### ISSUE TITLE
SVG HELP!

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/EmilyDickinson16#28]
@ebeshero @ghbondar So I'm helping @brookestewart with the SVG.  I am trying to find the total dashes (`&#8212;`) in each original Dickinson poem.  So this is the XPath that I came up with to search for them: `count(//rdg[@wit[contains(., '#df16') or contains(., 'var0') or contains(., 'var1') or contains(., 'var2')]][contains(., '&#8212;')])`
Sorry it's super long!  It seemed to me that it would work correctly.  I counted the dashes myself in poem 1, and it should be giving me 21; however, it is only giving me 17...any suggestions???

**Comment by ebeshero** [comment]
@nlottig94 Before I check the poem itself, tell me if there is a chance a dash character could be sitting outside an `<rdg>` element?

**Comment by nlottig94** [comment]
I don't believe there are.

**Comment by ebeshero** [comment]
Just took a look at poem 1, and you're right, they're all inside rdg elements. Actually I think you're missing some dashes because you're not actually counting the dashes themselves, but instead the parent elements that contain them! A few of these elements probably contain multiple dashes.

So you want to be counting the dash characters directly, in any elements' text node. Let's see if we can figure out a way...

**Comment by nlottig94** [comment]
Okay, I'll look at it tomorrow.  I'm not at my computer right now.

**Comment by amielnicki** [comment]
It's because it is counting the instances of rdg that have a dash in them, so it is esentially counting the lines... for example, if you run this `//rdg[@wit[contains(., '#df16') or contains(., 'var0') or contains(., 'var1') or contains(., 'var2')]][contains(., '&#8212;')]` it shows you what the 17 are.

I am thinking about how to count the dashes

**Comment by alexthattalks** [comment]
Opps, didn't mean to do that! I was typing a similar thought to @ebeshero and hit the wrong button lol

**Comment by ebeshero** [comment]
I'm checking Michael Kay, and I think what we want is analyze-string--but let me check...

**Comment by ebeshero** [comment]
Read about `<xsl:analyze-string>` in Michael Kay, pages 230+...and some examples around 907-908...

I think I know how to write this...

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart @amielnicki I tried a few strategies last night and this morning, and it's not quite right! But first of all, I made some corrections to your xsl:stylesheet so it would read TEI, and I found a reliable strategy for plotting the x position of your dots. What's not working is counting the hyphens...yet. I'm confident we'll figure it out, but I pushed what I have so far:

See: https://github.com/ebeshero/EmilyDickinson16/blob/master/xslt_to_SVG.xsl 

You'll see that I've experimented with a couple of variables, and I need to explain to you how this works if I can get it to work. There may well be a simpler way to do this, so I'm going to ask for a little help myself. 
@djbpitt

**Comment by ebeshero** [comment]
@djbpitt Hi David! I wonder if you can help us here: We're looking for a good strategy to do the following on the Dickinson project:
- The Dickinson team is working on preparing SVG graphs to compare how much the different editions reduced Emily Dickinson's hyphens. They're running XSLT over a collection of files (using collection()) in the directory in this GitHub repository called "Dickinson", and for right now, they're just working on counting the hyphens wherever they appear in each poem. 
- Each of the 11 TEI files in the Dickinson directory or collection contains a poem inside its `<body>` element, and inside those poems (nearly always inside an `<rdg>` element) are hyphens which we've indicated with this special character: &#8212;  
  The team did not mark those hyphens with anything (didn't use the `<punct>` element for example). 
- I thought we could grab and count the hyphens with xsl:analyze-string() , and I'm running into some interesting snags possibly to do with our use of collection(), though I'm not sure. The strategy I tried is basically this:

1) Define a variable named `$hyphenX` in XSLT, and make its value is dependent on applying-templates on the `<rdg>` elements in each TEI file.  (Really I think we want to make this run over _any element whose text-node contains the hyphen character_, and that's how I first wrote this, but I retrenched just simply to reach into the `<rdg>` elements when I wasn't generating good output.) Note my positioning of this, which _could_ be problematic: I've set this inside an `xsl:for-each` that is looping through each file in the collection and generating me some variables and then drawing our circles for dots on the SVG graph.

2) In the template rule matching on `rdg[contains(., '&#8212;')]`, I am attempting to use `<xsl:analyze-string>` to reach in and internally match on a hyphen character, and then to output a character, an arbitrary letter X. I'm doing that so I can construct a string of X's: so that every time the parser finds a hyphen, it outputs an X, and starts building a little string of these. That string of X's should be the same string-length as the number of hyphens in the document (at least if I've understood this right). 

3) Then back up in the xsl:for-each looping through my poems, I create another variable called `$hyphenCount` that calculates the string-length() of the string of X's I think I should have generated. 

The problem is: Apparently I _am_ generating lots of X's, and it looks like a different number for each poem, but I'm getting much too many: in the 400s through 600s, when the numbers should be more like the 20s to 30s. Can anyone help figure out what's going wrong here? I bet it's something to do with overcalculating or getting repeated counts somehow--some way in which I've framed how our looping through the poems and/or the rdg elements works.

It may be my strategy is too complex, so maybe let's see if we can figure out a simpler way to do this!
(In working out this strategy, I'm patching together some advice ( See among others: http://stackoverflow.com/questions/6679705/count-the-number-of-occurrences-of-a-string-in-xml-using-xslt ) that used to do things like this with `<xsl:call-template>` in XSLT 1.0...and from reading Michael Kay (p. 271), I don't think we need to use that any more and `<xsl:analyze-string>` ought to be able to do much the same thing. So this is my attempt to do much the same thing...)

**Comment by djbpitt** [comment]
Dear Elisa and everyone else,

It looks as if you're defining $hyphenX as equal to a <rdg> element and
then $hyphenCount as the string-length() of that entire <rdg>. I think what
you want in order count the hyphens in the <rdg> is to set $hyphenCount to
something like:

string-length($hyphenX) - string-length(translate($hyphenX,'-',''))

This strips the hyphens from $hyphenX (on the right) and subtracts its
length without hyphens from its length with hyphens, and the difference
should be the count of hyphens.

I just peeked at that bit of XSLT code, so I haven't explored the rest or
tried to run the transformation, but I hope this is nonetheless helpful.

Best,

David

**Comment by ebeshero** [comment]
I'm finally looking back at this after a busy day! A quick correction for everyone: We should be calling these **dashes** (not hyphens). We're using a dash character. In your write-ups on Dickinson for the site, you really don't want to call these hyphens!

**Comment by ebeshero** [comment]
@djbpitt  Okay, a follow-up question: When I write this code:

```
<xsl:template match="rdg[contains(., '&#8212;')]">
        <xsl:analyze-string select="." regex="&#8212;">
            <xsl:matching-substring >
             <xsl:text>X</xsl:text>   
            </xsl:matching-substring>

        </xsl:analyze-string>
    </xsl:template>
```

should it not reach into the `<rdg>` element, analyze the string there for the dash character, and THEN, in `<xsl:matching-substring>` output a letter X every time it encounters the dash (identified with the `@regex` in `<xsl:analyze-string>`? I suspect with you that this is not happening and instead I'm outputting X's for the entire string of characteers in the rdg element, which means analyze-string isn't doing what I think it should be doing, but I don't know why not. I suppose my dash character isn't a literal regex but an actual unicode character, and I wondered if it wouldn't work because of that, but...I think it _ought_ to isolate those dashes unless I'm misunderstanding how xsl:matching-substring  works(?)

**Comment by ebeshero** [comment]
@djbpitt @nlottig94 @brookestewart @amielnicki Thanks to David's advice I worked out an alternative solution, which I've commented on in this commit: https://github.com/ebeshero/EmilyDickinson16/commit/0e1de33d363022c241bbc879924bf643b85995dd

If you can follow what I've started here, I think you'll be in good shape to continue with calculating your percentages. **Beware of my testOutput SVG**, which looks pretty but isn't correct! It's just outputting raw counts multiplied by a $y-interval, and this has nothing to do with your y-axis as you've plotted it.

**Comment by djbpitt** [comment]
GIven this XML:

<?xml version="1.0" encoding="UTF-8"?>
<root>
    <p>blah—blah—blah——blah</p>
</root>

and this XLST:

<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
exclude-result-prefixes="xs" version="2.0">
    <xsl:template match="/">
        <root>
            xsl:apply-templates/
        </root>
    /xsl:template
    <xsl:template match="p">
        <xsl:analyze-string select="." regex="&#8212;">
            xsl:matching-substring
                xsl:textX/xsl:text
            /xsl:matching-substring
        /xsl:analyze-string
    /xsl:template
/xsl:stylesheet

I get this result:

<?xml version="1.0" encoding="UTF-8"?><root>
    XXXX
</root>

which is what I expect: one 'X' for each em-dash. Is that not what you get?

**Comment by ebeshero** [comment]
@djbpitt That's what I'd _expect_ to get, and why I thought my strategy with `xsl:analyze-string` would work. But instead it counted way too many characters--in the 400s and 600s, not the 20s or 30s we expect. My hunch is it had to do with my positioning of the variable definition within XSL:for-each, but that is set to look at each of the 11 files one at a time. I wonder if reaching into a new template was looking through the poem plus the whole collection somehow?  

I am glad that my strategy works in principle, but the practice of deploying it over a collection from within for-each seems to multiply the dashes! I wish I knew why--but do you think it's to do with the collection()? In other words, what if you had a collection of 11 files like this?

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <p>blah—blah—blah——blah</p>
</root>
```

The XSLT I tried was something like this (pared down without SVG stuff):

```
   <xsl:variable name="DickinsonColl" select="collection('Dickinson')"/>
  <xsl:template match="/">
 <xsl:for-each select="$DickinsonColl//TEI">
               <xsl:variable name="dashX">
                     <xsl:apply-templates select=".//rdg"/>
                  </xsl:variable>  
            <xsl:text>Dash Count! </xsl:text>
<xsl:value-of select="string-length($dashX)"/>

    </xsl:for-each>
     </xsl:template>

<xsl:template match="rdg[contains(., '&#8212;')]">
    <xsl:analyze-string select="." regex="&#8212;">
          <xsl:matching-substring >
          <xsl:text>X</xsl:text>   
         </xsl:matching-substring>       
   </xsl:analyze-string>
   </xsl:template>

```

Why do I generate such massive string-lengths with this? I don't think it would be giving me the length of the rdg elements which actually _don't_ contain hundreds of characters...they are quite short--part of a Dickinson line. I think the problem must be with the template match on rdg, so my new solution doesn't involve a new template.

**Comment by ebeshero** [comment]
@djbpitt @nlottig94 @brookestewart @amielnicki See [my latest commit of the XSLT file](https://github.com/ebeshero/EmilyDickinson16/blob/3b197bfec97abcdf04e116c6547324912c3901f6/xslt_to_SVG.xsl). 
 I just figured out how to get `<xsl:analyze-string>` to work, and it outputs the same (good) results) as the first way that worked yesterday. I want to show you Dickinsonians both approaches so you can decide which one you want to keep using. I imagine that you'll need to keep making calculations to study alterations of various kinds or dash removal, etc, or simply to think about **differences in string-length()** within the published versions.

If you understand how `<xsl:analyze-string>` works (read about it in Michael Kay), you might want to try using it to isolate other kinds of punctuation marks coded in your <app> elements to help you compare the kinds of punctuation alterations you're seeing the various editors make. Some notes:
1) You don't need its `@regex` attribute to be a literal regular expression, but you can set it on an actual character (period, comma, etc.) 

2) Inside `<xsl:analyze-string>`I've been using `<xsl:matching-substring>` to isolate one character and process it in some way. Think about your strategy for studying the published editions and how they compare to this. You may want to experiment  more with the following:
- **string-length()**:  Consider how one string-length() in a <rdg> compares with the string-length of Dickinson's original. Complication: you'll want to include Dickinson's variants (inside their own `<rdg>` elements) to get the full picture of how much is cut or added.
- Within `<xsl:analyze-string>` try using `<xsl:non-matching-substring>` to process everything that does NOT match your `@regex` (including getting its string-length, among other things).

Hope this helps!

**Comment by nlottig94** [comment]
THE SVG IS FINISHED!!!!  However, @amielnicki  I can't figure out where to paste the svg in the dash html...So the svg is not in a folder.  It is named `Dickinson_SVG.svg`.  Let me know what to do @amielnicki

**Comment by ebeshero** [comment]
I think Alex told us how he expected it to come in when we were on the phone earlier but I'm sorry I don't recall the details. I _think_ he just said to paste it on the page. What happens when you do that--is it visible? 

For guidance on positioning SVG on the HTML page, see our [JavaScript Exercise 3](http://newtfire.org/dh/JavaScript_Exercise3.html) and look in the third bullet point under "Some guidance for stepping your way to a solution."

**Comment by ebeshero** [comment]
And really, this should help: https://css-tricks.com/scale-svg/

**Comment by alexthattalks** [comment]
It is live on the site!!  http://dickinson16.newtfire.org/dash.html

**Comment by nlottig94** [comment]
It looks awesome @ebeshero !!!!!!!   CHECK IT OUT EVERYONE!!!  @blawrence719 @brookestewart @ghbondar   And thank you for your input @djbpitt !

**Comment by ebeshero** [comment]
@amielnicki @nlottig94 @blawrence719 @brookestewart Wow! That was speedy work, everyone, and what a fascinating graph! I see Brooke Lawrence's intro, about, and conclusion pages are up now, too, and I like what you've done to flesh out the story of our repurposing from Michele Ierardi's old student site. Here are some questions for the team, since I know you're still working on this for another day, maybe two if you need it:

1) Will you prepare a bibliography of the print and ms editions you worked with? You may want it on the SVG page to explain the symbols in your colorful legend.

2) You should discuss the findings of your dash analysis, and it might make sense to do so on the same page with the graph. What other kinds of analysis might this lead to, if you were going to continue to study how Dickinson's punctuation was altered by later editions?

3) How about a link (multiple links?) to your project GitHub, to highlight your fancy code work? You might discuss Alex's XSLT for the poem interface, Nicole's and Alex's use of image maps, your approach to calculating the percentage of reduction in dashes in the print editions...I bet a lot of this is coming in your Methodology page.

4) Somewhere in the Home or About page is a mention of the old Assumptions page, which you'll want to update to the new page.

Really brilliant work so far, everyone!

**Comment by brookestewart** [comment]
@ebeshero I have the dash analysis finished except for the bibliography. I could remove some of the bibliographical info from the paragraph that explains the abbreviations and leave just the full title once the bibliography is finished, and just have viewers reference that for more info. 
 Should I do it the way it is here: http://www.cs.virginia.edu/~ajf2j/emily/stab.html or MLA format? Does it matter?

**Comment by ebeshero** [comment]
@brookestewart Follow the style for citations that I posted in our 19c Brit Lit Annotation Research Assignment: http://newtfire.org/19cBrit/AnnotResearchAssign.html. MLA style makes sense. You may want to add comments to each entry of the bibliography to provide a little information about each work. Read more about these editions here: https://www.emilydickinsonmuseum.org/posthumous_publication

@blawrence719 linked to that page on the home page she developed.
