### ISSUE TITLE
What we did for this week!!

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/EmilyDickinson16#7]
@brookestewart and I combined our tables that we created for XSLT Exercise 7!  It looks awesome!!  Check it out!

**Comment by nlottig94** [comment]
So @brookestewart and I are splitting up the poems so we can read through them and make sure there aren't any transcription errors for next week!!

**Comment by ebeshero** [comment]
Yay! I'm looking forward to checking it out shortly...

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart Is your new table on this page?
https://github.com/ebeshero/EmilyDickinson16/blob/master/lottig_10-30_xsltExercise7.xsl

If so, I like your color scheme. But let's not be making the poem's lines align center. That's not the way these poems would conventionally be formatted anyway: you want to align them left, but you want to move your left margin over so you're essentially positioning the poems in the center of the page. (I realize this is a carry over from typographic (print) layout, but aligning center isn't quite what's happening with th handwritten manuscript either.)

Since Dickinson was writing in ballad meter, one convention with representing that is to indent every other line. I don't think that's necessary here, but you might try it to see how it looks. Or have a look at Harvard's Emily Dickinson Archive just to see how they're laying out their transcriptions, and give this some thought. It's worth a conversation here to decide on your strategy for laying out the texts. https://github.com/ebeshero/EmilyDickinson16/wiki/Resources-for-Emily-Dickinson-Research
